#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile virtualenv27
  mkdir -p "$shome/bin"
  ln -nfs ../vendor/virtualenv/bin/pip "$shome/bin/pip27"
  ln -nfs ../vendor/virtualenv/bin/virtualenv "$shome/bin/virtualenv27"
  ln -nfs ../vendor/virtualenv/bin/pipenv "$shome/bin/pipenv27"
  ln -nfs ../vendor/virtualenv/bin/flake8 "$shome/bin/flake27"
}

main "$@"
