#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  local ver_py27="$(python --version 2>&1 | awk '$1 == "Python" {print $2}' || true)"
  jq -n --arg py27 "$ver_py27" '{py27: $py27}'
}

version "$@"
