#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  local ver_py27="$(python --version 2>&1 | awk '$1 == "Python" {print $2}' || true)"
  local ver_pipenv27="$(pipenv --version 2>&1 | awk '{print $3}' || true)"
  jq -n --arg py27 "$ver_py27" --arg pipenv27 "$ver_pipenv27" '{py27: $py27, pipenv27: $pipenv27}'
}

version "$@"
