#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_py27="0.0.1"
  jq -n --arg py27 "$ver_py27" '{py27: $py27}'
}

version "$@"
